version: '3.8'

services:
    web:
        build:
            context: envoirment/dev/nginx
        container_name: mortgage-web
        volumes:
            - .:/application
        networks:
            - mortgage-dev
        ports:
            - ${EXTERNAL_WEBSERVER_PORT:-80}:80
        restart: unless-stopped
        depends_on:
            - php
            - database
            - database-test

    php:
        build:
            context: envoirment/dev/php
            args:
                INSTALL_XDEBUG: ${DOCKER_INSTALL_XDEBUG:-false}
        container_name: mortgage-php
        working_dir: /application
        user: ${CURRENT_UID:-1000}
        volumes:
            - .:/application
            - ./envoirment/dev/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - mortgage-dev
        restart: unless-stopped

    database:
        image: mysql:8.0
        container_name: mortgage-db-dev
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - ${EXTERNAL_DATABASE_PORT:-3306}:3306
        volumes:
            - mortgage-mysql-data:/var/lib/mysql
        networks:
            - mortgage-dev
        restart: unless-stopped

    database-test:
        image: mysql:8.0
        container_name: mortgage-db-test
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - ${EXTERNAL_TEST_DATABASE_PORT:-3307}:3306
        networks:
            - mortgage-dev
        restart: unless-stopped

    node:
        image: node:18.4-alpine3.16
        container_name: mortgage-node
        working_dir: /application
        volumes:
            - .:/application
        ports:
            - ${EXTERNAL_NODE_PORT:-3000}:3000
        networks:
            - mortgage-dev
        stdin_open: true
        tty: true
        restart: unless-stopped

networks:
    mortgage-dev:
        driver: bridge

volumes:
    mortgage-mysql-data:
        name: mortgage-mysql-data
